### PR TITLE
doc: let type inference do its job

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by gustavla** [comment]
If type is omitted here, it will assume `i32`, which is another benchmark. Either is reasonable of course, it depends on what you want timed. However, using the type inference do its job here means it is less clear which benchmark you are actually doing, so I think being explicit is preferred here.

**Comment by tshepang** [comment]
I checked both i32 and i64, and performance was the same.

**Comment by gustavla** [comment]
Increase loop to 1000_000 and you will see a noticable difference between i32 and i64. I got:

```
10 loops: 11.2812 ms   // i64
100 loops: 4.88423 ms  // inferred (i32)
```

**Comment by tshepang** [comment]
ok, good to know

**Pull request closed without merging**
